version: '3.4'

services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: TransactionDB
        ports: 
            - "5432:5432"
        volumes:
            - dbdata:/var/lib/postgresql/data

    web:
        build: 
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DevConnection=Server=db;Port=5432;Database=TransactionDB;User Id=postgres;Password=postgres;
        ports:
            - "8000:80"
        volumes:
            - .:/src

volumes:
    dbdata:
