version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  db:
    build: ./Database
    restart: always
    ports:
      - "5432:5432"
    networks:
      - db
      
networks:
  db:
    driver: bridge
